import assert from "node:assert/strict"
import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import test from "node:test"

const repo = path.resolve(import.meta.dirname, "..")
const cli = path.join(repo, "bin", "agentcfg")

function env(root: string, overrides: Record<string, string> = {}) {
    return {
        ...process.env,
        HOME: root,
        AGENTCFG_STATE_HOME: path.join(root, ".agentcfg"),
        AGENTCFG_REPO_ROOT: repo,
        ...overrides,
    }
}

function run(args: string[], root = mkdtempSync(path.join(tmpdir(), "agentcfg-")), overrides: Record<string, string> = {}) {
    const res = spawnSync(cli, args, {
        cwd: repo,
        env: env(root, overrides),
        encoding: "utf8",
    })
    return { ...res, root }
}

test("validate checks repository contracts", () => {
    const res = run(["validate"])
    assert.equal(res.status, 0, res.stderr)
    assert.match(res.stdout, /validate ok/)
})

test("render outputs generated instruction header and target overlay", () => {
    const res = run(["render", "claude"])
    assert.equal(res.status, 0, res.stderr)
    assert.equal(res.stdout.startsWith("<!--\nGenerated by agentcfg"), true)
    assert.doesNotMatch(res.stdout, /^===== claude =====/)
    assert.match(res.stdout, /Generated by agentcfg/)
    assert.match(res.stdout, /Claude Code 特定要求/)
    assert.match(res.stdout, /~\/\.claude\/CLAUDE\.md/)
})

test("install dry-run does not write manifest or target files", () => {
    const res = run(["install", "codex", "--profile", "minimal", "--dry-run"])
    assert.equal(res.status, 0, res.stderr)
    assert.match(res.stdout, /\[dry-run\] install codex:instructions/)
    assert.equal(existsSync(path.join(res.root, ".agentcfg", "manifest.json")), false)
    assert.equal(existsSync(path.join(res.root, ".codex", "AGENTS.md")), false)
})

test("full dry-run includes OpenCode regression assets", () => {
    const res = run(["install", "opencode", "--profile", "opencode-full", "--dry-run"])
    assert.equal(res.status, 0, res.stderr)
    assert.match(res.stdout, /opencode:opencode-config/)
    assert.match(res.stdout, /opencode:opencode-agents/)
    assert.match(res.stdout, /opencode:opencode-commands/)
    assert.match(res.stdout, /opencode:opencode-plugins/)
})

test("profile target whitelist rejects explicit mismatches", () => {
    const res = run(["install", "codex", "--profile", "opencode-full", "--dry-run"])
    assert.notEqual(res.status, 0)
    assert.match(res.stderr, /profile opencode-full 不支持 target：codex/)
})

test("install writes manifest and backs up pre-existing non-managed files", () => {
    const root = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const agents = path.join(root, ".codex", "AGENTS.md")
    mkdirSync(path.dirname(agents), { recursive: true })
    writeFileSync(agents, "local custom file\n", { flag: "w" })

    const res = run(["install", "codex", "--profile", "minimal"], root)
    assert.equal(res.status, 0, res.stderr)

    const manifest = JSON.parse(readFileSync(path.join(root, ".agentcfg", "manifest.json"), "utf8"))
    assert.equal(manifest.entries.some((entry: any) => entry.target === "codex" && entry.asset === "instructions"), true)
    assert.match(readFileSync(agents, "utf8"), /Generated by agentcfg/)
    assert.equal(manifest.entries.some((entry: any) => entry.backup), true)
})

test("install does not exclude legitimate asset names containing log substrings", () => {
    const root = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const res = run(["install", "opencode", "--profile", "opencode-full"], root)
    assert.equal(res.status, 0, res.stderr)
    assert.equal(existsSync(path.join(root, ".config", "opencode", "plugin", "delegation-logger.ts")), true)
    assert.equal(existsSync(path.join(root, ".config", "opencode", "skills", "webapp-testing", "examples", "console_logging.py")), true)
})

test("uninstall only removes managed entries", () => {
    const root = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const keep = path.join(root, ".codex", "keep.md")
    mkdirSync(path.dirname(keep), { recursive: true })

    const install = run(["install", "codex", "--profile", "minimal"], root)
    assert.equal(install.status, 0, install.stderr)
    writeFileSync(keep, "not managed\n")

    const uninstall = run(["uninstall", "codex"], root)
    assert.equal(uninstall.status, 0, uninstall.stderr)
    assert.equal(existsSync(path.join(root, ".codex", "AGENTS.md")), false)
    assert.equal(existsSync(keep), true)
})

test("restore brings back files and matching manifest entries", () => {
    const root = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const install = run(["install", "codex", "--profile", "minimal"], root)
    assert.equal(install.status, 0, install.stderr)

    const backup = run(["backup", "codex"], root)
    assert.equal(backup.status, 0, backup.stderr)
    const uninstall = run(["uninstall", "codex"], root)
    assert.equal(uninstall.status, 0, uninstall.stderr)

    const restore = run(["restore", "latest"], root)
    assert.equal(restore.status, 0, restore.stderr)
    const status = run(["status"], root)
    assert.equal(status.status, 0, status.stderr)
    assert.match(status.stdout, /ok\s+codex:instructions/)
    assert.match(status.stdout, /ok\s+codex:shared-skills/)
})

test("link mode diff follows symlinked directory contents", () => {
    const root = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const install = run(["install", "codex", "--profile", "minimal", "--link"], root)
    assert.equal(install.status, 0, install.stderr)

    const diff = run(["diff", "codex", "--profile", "minimal"], root)
    assert.equal(diff.status, 0, diff.stderr)
    assert.match(diff.stdout, /same\s+codex:instructions/)
    assert.match(diff.stdout, /same\s+codex:shared-skills/)
    assert.doesNotMatch(diff.stdout, /diff\s+codex:shared-skills/)
})

test("doctor detects sensitive files even though managed scans exclude them", () => {
    const home = mkdtempSync(path.join(tmpdir(), "agentcfg-"))
    const tempRepo = path.join(home, "repo")
    mkdirSync(tempRepo, { recursive: true })
    for (const dir of ["assets", "profiles", "targets", "templates"]) {
        symlinkSync(path.join(repo, dir), path.join(tempRepo, dir), "dir")
    }
    writeFileSync(path.join(tempRepo, "token.txt"), "not a real token\n")

    const res = run(["doctor"], home, { AGENTCFG_REPO_ROOT: tempRepo })
    assert.equal(res.status, 0, res.stderr)
    assert.match(res.stdout, /suspicious files:/)
    assert.match(res.stdout, /token\.txt/)
})

test("rollback without --apply is a read-only plan", () => {
    const res = run(["rollback", "HEAD"])
    assert.equal(res.status, 0, res.stderr)
    assert.match(res.stdout, /未执行回滚/)
})

test("rollback reports invalid refs as failures", () => {
    const res = run(["rollback", "not-a-real-ref"])
    assert.notEqual(res.status, 0)
    assert.match(res.stderr, /not-a-real-ref/)
})
